<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'b419c11b924de79ffa740afc29a3dc16' => $baseDir . '/foo.php',
    'f558c96fbd0535aaa98981fa59ff7594' => $baseDir . '/bar.php',
);
