<?php

// autoload_files.php generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

require $vendorDir . '/c/lorem/testC.php';
require $vendorDir . '/z/foo/testA.php';
require $vendorDir . '/d/d/testD.php';
require $vendorDir . '/b/bar/testB.php';
require $vendorDir . '/e/e/testE.php';
require $baseDir . '/root.php';