<?php

// autoload_checkFilesAutoload.php generated by Composer

if (class_exists('ComposerAutoloaderInitFilesAutoload', false)) {
    $loader = ComposerAutoloaderInitFilesAutoload::getLoader();
    $vendorDir = dirname(__DIR__);
    $baseDir = dirname($vendorDir);

    $map = require __DIR__ . '/autoload_namespaces.php';
    foreach ($map as $namespace => $path) {
        $loader->add($namespace, $path);
    }

    $classMap = require __DIR__ . '/autoload_classmap.php';
    if ($classMap) {
        $loader->addClassMap($classMap);
    }

    $loader->register();

        require $baseDir . '/root.php';
        require $vendorDir . '/a/a/test.php';
        require $vendorDir . '/b/b/test2.php';

    return $loader;
}

return require __DIR__ . '/autoload_realFilesAutoload.php';
