<?php

// autoload_realTargetDir.php generated by Composer

require __DIR__ . '/ClassLoader.php';

class ComposerAutoloaderInitTargetDir
{
    public static $loader;
    
    public static function getLoader()
    {
        if(self::$loader == null){
            self::$loader = new \Composer\Autoload\ClassLoader();
            self::$loader->register();
        }
        $vendorDir = dirname(__DIR__);
        $baseDir = dirname($vendorDir);

        $map = require __DIR__ . '/autoload_namespaces.php';
        foreach ($map as $namespace => $path) {
            self::$loader->add($namespace, $path);
        }

        $classMap = require __DIR__ . '/autoload_classmap.php';
        if ($classMap) {
            self::$loader->addClassMap($classMap);
        }

        spl_autoload_register(array('ComposerAutoloaderInitTargetDir', 'autoload'));

        return self::$loader;
    }

    public static function autoload($class)
    {
        $dir = dirname(dirname(__DIR__)) . '/';
        $prefixes = array('Main\\Foo', 'Main\\Bar');
        foreach ($prefixes as $prefix) {
            if (0 !== strpos($class, $prefix)) {
                continue;
            }
            $path = $dir . implode('/', array_slice(explode('\\', $class), 2)).'.php';
            if (!$path = stream_resolve_include_path($path)) {
                return false;
            }
            require $path;

            return true;
        }
    }
}
