<?php

// autoload_realFilesAutoload.php generated by Composer

require __DIR__ . '/ClassLoader.php';

class ComposerAutoloaderInitFilesAutoload
{
    public static $loader;
    
    public static function getLoader()
    {
        if(self::$loader == null){
            self::$loader = new \Composer\Autoload\ClassLoader();
            self::$loader->register();
        }
        $vendorDir = dirname(__DIR__);
        $baseDir = dirname($vendorDir);

        $map = require __DIR__ . '/autoload_namespaces.php';
        foreach ($map as $namespace => $path) {
            self::$loader->add($namespace, $path);
        }

        $classMap = require __DIR__ . '/autoload_classmap.php';
        if ($classMap) {
            self::$loader->addClassMap($classMap);
        }

        require $vendorDir . '/a/a/test.php';
        require $vendorDir . '/b/b/test2.php';

        return self::$loader;
    }
}
