<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    $vendorDir . '/a/a/test.php',
    $vendorDir . '/b/b/test2.php',
    $vendorDir . '/c/c/foo/bar/test3.php',
    $vendorDir . '/c/c/foo/bar/test4.php',
    $baseDir . '/root.php',
);
