<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInitFilesAutoload
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        spl_autoload_register(array('ComposerAutoloaderInitFilesAutoload', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInitFilesAutoload', 'loadClassLoader'));

        // include InstalledVersions class & installed.php data to ensure it is in opcache when preloading
        if (file_exists(__DIR__ . '/InstalledVersions.php') && !class_exists('Composer\\InstalledVersions', false)) {
            include __DIR__ . '/InstalledVersions.php';
            include __DIR__ . '/installed.php';
        }

        require __DIR__ . '/autoload_static.php';
        call_user_func(\Composer\Autoload\ComposerStaticInitFilesAutoload::getInitializer($loader));

        $loader->register(true);

        return $loader;
    }
}
