<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'ca64fb7d3f21566080b945f028f30a2e' => $baseDir . '/devfiles/foo.php',
);
