<?php

// autoload_namespace.php generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Main' => $baseDir . '/src/',
    'Lala' => array($baseDir . '/src/', $baseDir . '/lib/'),
);
