<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    '61b776fd0ee84fb7d7d958ae46118ded' => $baseDir . '/root.php',
);
