<?php

// autoload_namespaces.php generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = $vendorDir;

return array(
    'Main' => $vendorDir . '/src',
    'Lala' => $vendorDir . '/src',
);
