<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Main\\ClassMain' => $baseDir . '/src/Main/ClassMain.php',
);
