<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(__FILE__, 2);
$baseDir = dirname($vendorDir);

return array(
    'ClassMapBar' => $baseDir . '/lib/rootbar.php',
    'ClassMapFoo' => $baseDir . '/src/rootfoo.php',
);
