<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitTargetDir
{
    public static $files = array (
        'b419c11b924de79ffa740afc29a3dc16' => __DIR__ . '/../..' . '/foo.php',
        'f558c96fbd0535aaa98981fa59ff7594' => __DIR__ . '/../..' . '/bar.php',
    );

    public static $prefixesPsr0 = array (
        'M' => 
        array (
            'Main\\Foo' => 
            array (
                0 => __DIR__ . '/../..' . '/',
            ),
            'Main\\Bar' => 
            array (
                0 => __DIR__ . '/../..' . '/',
            ),
        ),
    );

    public static $classMap = array (
        'ClassMapBar' => __DIR__ . '/../..' . '/lib/rootbar.php',
        'ClassMapFoo' => __DIR__ . '/../..' . '/src/rootfoo.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixesPsr0 = ComposerStaticInitTargetDir::$prefixesPsr0;
            $loader->classMap = ComposerStaticInitTargetDir::$classMap;

        }, null, ClassLoader::class);
    }
}
