<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    $baseDir . '/root3.php',
    $vendorDir . '/c/lorem/testCp.php',
    $vendorDir . '/d/d/testDp.php',
    $vendorDir . '/b/bar/testBp.php',
    $vendorDir . '/e/e/testEp.php',
    $vendorDir . '/z/foo/testAp.php',
);
