<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitFilesAutoloadOrderPrepended
{
    public static $files = array (
        '6a4fbeb1a77f0eeb3601a42bb9f00b2a' => __DIR__ . '/../..' . '/root3.php',
        '1777e75b6caf94cc1cf2ffaf28230e1e' => __DIR__ . '/..' . '/c/lorem/testCp.php',
        'b51007dab66e8c8bfbcf5c94d246e93f' => __DIR__ . '/..' . '/d/d/testDp.php',
        '6a7c836332ea77b008a7633db1964f10' => __DIR__ . '/..' . '/b/bar/testBp.php',
        'a956466fb472d7edbb2277f75dd10276' => __DIR__ . '/..' . '/e/e/testEp.php',
        '8a6ba80d91ca5241d92fffc9cd3abd30' => __DIR__ . '/..' . '/z/foo/testAp.php',
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->classMap = ComposerStaticInitFilesAutoloadOrderPrepended::$classMap;

        }, null, ClassLoader::class);
    }
}
