<?php

// autoload_namespace.php generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'B\\Sub\\Name' => $vendorDir . '/b/b/src/',
    'A\\B' => array('/home/deveuser/local-packages/a-a/lib', $vendorDir . '/a/a/lib/'),
    'A' => $vendorDir . '/a/a/src/',
);
