<?php

// autoload_checkFilesAutoloadOrder.php generated by Composer

if (class_exists('ComposerAutoloaderInitFilesAutoloadOrder', false)) {
    $loader = ComposerAutoloaderInitFilesAutoloadOrder::getLoader();
    $vendorDir = dirname(__DIR__);
    $baseDir = dirname($vendorDir);

    $map = require __DIR__ . '/autoload_namespaces.php';
    foreach ($map as $namespace => $path) {
        $loader->add($namespace, $path);
    }

    $classMap = require __DIR__ . '/autoload_classmap.php';
    if ($classMap) {
        $loader->addClassMap($classMap);
    }

    $loader->register();

        require $vendorDir . '/c/lorem/testC.php';
        require $vendorDir . '/z/foo/testA.php';
        require $baseDir . '/root.php';
        require $vendorDir . '/b/bar/testB.php';
        require $vendorDir . '/d/d/testD.php';
        require $vendorDir . '/e/e/testE.php';

    return $loader;
}

return require __DIR__ . '/autoload_realFilesAutoloadOrder.php';
