<?php

// autoload_namespace.php generated by Composer

$vendorDir = dirname(__DIR__);

return array(
    'B\\Sub\\Name' => $vendorDir . '/b/b/src/',
    'A\\B' => '/home/deveuser/local-packages/a-a/lib',
    'A' => $vendorDir . '/a/a/src/',
);
