<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = $vendorDir;

return array(
    'Acme\\Fruit\\' => array($vendorDir . '/src-fruit'),
    'Acme\\Cake\\' => array($vendorDir . '/lib-cake', $vendorDir . '/src-cake'),
);
