<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(__FILE__, 2);
$baseDir = dirname($vendorDir);

return array(
    'Main' => array($baseDir . '/src', $baseDir . '/tests'),
);
