<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'ClassMapBar' => $baseDir . '/lib/rootbar.php',
    'ClassMapFoo' => $baseDir . '/src/rootfoo.php',
);
