<?php

// autoload_namespace.php generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname(dirname($vendorDir));

return array(
    'Main' => $baseDir . '/src/',
    'Lala' => $baseDir . '/src/',
);
