<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname($vendorDir));

return array(
    'ClassMapFoo' => $baseDir . '/composersrc/foo.php',
);
