<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = $vendorDir;

return array(
    'ClassMapFoo' => $vendorDir . '/composersrc/foo.php',
    'Main\\Foo' => $vendorDir . '/src/Main/Foo.php',
);
