<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'ClassMapBar' => $vendorDir . '/b/b/ClassMapBar.php',
    'ClassMapBaz' => $vendorDir . '/c/c/foo/ClassMapBaz.php',
    'ClassMapFoo' => $vendorDir . '/a/a/src/ClassMapFoo.php',
);
