<?php

// autoload_namespaces.php generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'B\\Sub\\Name' => $vendorDir . '/b/b/src',
    'A\\B' => $vendorDir . '/a/a/lib',
    'A' => $vendorDir . '/a/a/src',
);
