<?php

// autoload_classmap.php generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'ClassMapBar' => $baseDir . '/composer-test-autoload/b/b/test.php',
    'ClassMapBaz' => $baseDir . '/composer-test-autoload/c/c/foo/test.php',
    'ClassMapFoo' => $baseDir . '/composer-test-autoload/a/a/src/a.php',
);
