<?php

// autoload_namespaces.php generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname($vendorDir));

return array(
    'Main' => $baseDir . '/src',
    'Lala' => $baseDir . '/src',
);
