<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(__FILE__, 2);
$baseDir = dirname($vendorDir, 2);

return array(
    'ClassMapFoo' => $baseDir . '/composersrc/foo.php',
);
