<?php

// autoload_realFilesAutoloadOrder.php generated by Composer

require __DIR__ . '/ClassLoader.php';

class ComposerAutoloaderInitFilesAutoloadOrder
{
    private static $loader;

    public static function getLoader()
    {
        if (null !== static::$loader) {
            return static::$loader;
        }

        static::$loader = $loader = new \Composer\Autoload\ClassLoader();
        $vendorDir = dirname(__DIR__);
        $baseDir = dirname($vendorDir);

        $map = require __DIR__ . '/autoload_namespaces.php';
        foreach ($map as $namespace => $path) {
            $loader->add($namespace, $path);
        }

        $classMap = require __DIR__ . '/autoload_classmap.php';
        if ($classMap) {
            $loader->addClassMap($classMap);
        }

        $loader->register();

        require $vendorDir . '/c/lorem/testC.php';
        require $vendorDir . '/z/foo/testA.php';
        require $baseDir . '/root.php';
        require $vendorDir . '/b/bar/testB.php';
        require $vendorDir . '/d/d/testD.php';
        require $vendorDir . '/e/e/testE.php';

        return $loader;
    }
}
