<?php

// autoload_moto.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Moto\\Fruit\\' => array($baseDir . '/src-moto-fruit'),
    'Moto\\Cake\\' => array($baseDir . '/src-moto-cake', $baseDir . '/lib-moto-cake'),
);
