<?php

// autoload.php @generated by Composer

require_once __DIR__ . '/composer' . '/autoload_real.php';

if (defined('COMPOSER_OPCACHE_OPTIMIZE') && COMPOSER_OPCACHE_OPTIMIZE == true) {
    return ComposerAutoloaderInitTargetDir::getLoader(true);
}

return ComposerAutoloaderInitTargetDir::getLoader(false);
