<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitMoto
{
    public static $prefixLengthsMoto = array (
        'M' =>
        array (
            'Moto\\Fruit\\' => 11,
            'Moto\\Cake\\' => 10,
        ),
    );

    public static $prefixDirsMoto = array (
        'Moto\\Fruit\\' =>
        array (
            0 => __DIR__ . '/../..' . '/src-moto-fruit',
        ),
        'Moto\\Cake\\' =>
        array (
            0 => __DIR__ . '/../..' . '/src-moto-cake',
            1 => __DIR__ . '/../..' . '/lib-moto-cake',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsMoto = ComposerStaticInitMoto::$prefixLengthsMoto;
            $loader->prefixDirsMoto = ComposerStaticInitMoto::$prefixDirsMoto;
            $loader->classMap = ComposerStaticInitMoto::$classMap;

        }, null, ClassLoader::class);
    }
}
