<?php

// autoload_classmap.php generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = $vendorDir;

return array(
    'Main\\Foo' => $baseDir . '/src/Main/Foo.php',
    'ClassMapFoo' => $baseDir . '/composersrc/foo.php',
);
