<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__FILE__, 2);
$baseDir = $vendorDir;

return array(
    'Acme\\Fruit\\' => array($vendorDir . '/src-fruit'),
    'Acme\\Cake\\' => array($vendorDir . '/src-cake', $vendorDir . '/lib-cake'),
);
