<?php

// autoload.php @generated by Composer

$phpVersionCheck = require_once __DIR__ . '/composer/php_version_check.php';
if (!$phpVersionCheck) {
    die('The PHP version you are running does not match the combination in your composer.lock. You likely ran "composer update" with a different PHP version than the one you are running right now!');
}

require_once __DIR__ . '/composer/autoload_real.php';

return ComposerAutoloaderInitFilesAutoloadOrder::getLoader();
