<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname($vendorDir));

return array(
    'Acme\\Fruit\\' => array($baseDir . '/src-fruit'),
    'Acme\\Cake\\' => array($baseDir . '/src-cake', $baseDir . '/lib-cake'),
);
