<?php

// platform_check.php @generated by Composer

$issues = array();

$lowerBound = '7.2.0.0.dev';
$upperBound = '8.0.0.0.dev';
$phpVersion = PHP_MAJOR_VERSION . '.' . PHP_MINOR_VERSION . '.' . PHP_RELEASE_VERSION . '0.0';

if (version_compare($phpVersion, $lowerBound, '<') || version_compare($phpVersion, $upperBound, '>=')) {
    $issues[] = sprintf('Your Composer dependencies require PHP in at least version %s and not higher than %s. You are running %s.',
        $lowerBound,
        $upperBound,
        PHP_VERSION
    );
}

$missingExtensions = array_diff(array (
  0 => 'json',
  1 => 'xml',
), array_map('strtolower', get_loaded_extensions()));

if (0 !== count($missingExtensions)) {
    $issues[] = 'Your Composer dependencies require the following PHP extensions to be installed: ' . implode(', ', $missingExtensions);
}

if (0 !== count($issues)) {
    die('Composer detected issues in your platform:' . "\n\n" . implode("\n", $issues));
}
