version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    labels: []

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "2.2"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    labels: []

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "1.10"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    labels: []
