<?php

// platform_check.php @generated by Composer

$issues = array();

if (!(PHP_VERSION_ID >= 70200)) {
    $issues[] = 'Your Composer dependencies require a PHP version ">= 7.2.0". You are running ' . PHP_VERSION  .  '.';
}

if ($issues) {
    trigger_error(
        'Composer detected issues in your platform: ' . implode(', ', $issues),
        E_USER_ERROR
    );
}
