<?php

// platform_check.php @generated by Composer

$issues = array();

$missingExtensions = array();
extension_loaded('json') || $missingExtensions[] = 'json';
extension_loaded('xml') || $missingExtensions[] = 'xml';

if ($missingExtensions) {
    $issues[] = 'Your Composer dependencies require the following PHP extensions to be installed: ' . implode(', ', $missingExtensions);
}

if ($issues && !headers_sent()) {
    header('HTTP/1.1 500 Internal Server Error');
    echo 'Composer detected issues in your platform:' . "\n\n" . implode("\n", $issues) . "\n\n";
    exit(104);
}
