name: Mark and close stale support issues

on:
  schedule:
  - cron: '32 1 * * *'

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions: {}

jobs:
  stale:
    name: "Mark and close stale support issues"

    runs-on: ubuntu-latest
    permissions:
      issues: write # for actions/stale to label/close stale issues
      pull-requests: write # for actions/stale to label/close stale pull requests

    steps:
    - uses: actions/stale@eb5cf3af3ac0a1aa4c9c45633dd1ae542a27a899 # v10.3.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-stale: 180
        days-before-close: 15
        stale-issue-message: 'This issue has been automatically marked Stale and will be closed in 15 days if no further activity happens.'
        stale-issue-label: 'Stale'
        only-labels: 'Support'
        exempt-all-milestones: true
        ascending: true
